"""
adelie/agents/tester_ai.py

Tester AI — generates test scripts and executes them via subprocess.

3-layer test structure matching Coder layers:
  Layer 0 (Unit)        — individual function/module tests
  Layer 1 (Integration) — cross-module / API integration tests
  Layer 2 (E2E)         — full system end-to-end tests

Test scripts are generated by LLM, saved to .adelie/tests/scripts/,
then executed safely with subprocess (whitelisted commands, timeout).
Results saved to .adelie/tests/results/.
"""

from __future__ import annotations

import json
import re
import shlex
import subprocess
from datetime import datetime
from pathlib import Path

from rich.console import Console

from adelie.config import WORKSPACE_PATH, PROJECT_ROOT
from adelie.llm_client import generate

console = Console()

TEST_ROOT = WORKSPACE_PATH.parent / "tests"
SCRIPTS_DIR = TEST_ROOT / "scripts"
RESULTS_DIR = TEST_ROOT / "results"

# Security: only these command prefixes are allowed
ALLOWED_COMMANDS = [
    "python", "python3", "pytest", "npm", "npx", "node",
    "go", "cargo", "curl", "wget", "cat", "ls", "echo",
    "pip", "pip3", "docker", "docker-compose",
]

# Dangerous flags that can enable arbitrary code execution
BLOCKED_FLAGS = {"-c", "--eval", "eval", "exec", "--exec", "-e"}

# Dangerous shell metacharacters
BLOCKED_CHARS = {";", "|", "&&", "||", "`", "$(", ">>", "<<"}

EXEC_TIMEOUT = 60  # seconds

SYSTEM_PROMPT = """You are Tester AI — a QA engineer in an autonomous AI loop.

You receive source code files and must generate test scripts to verify they work.

Output a single valid JSON object:
{
  "test_scripts": [
    {
      "name": "test_auth",
      "filename": "test_auth.py",
      "language": "python",
      "content": "full test script content...",
      "run_command": "python -m pytest .adelie/tests/scripts/test_auth.py -v",
      "test_layer": 0,
      "description": "Unit tests for authentication module"
    }
  ]
}

RULES:
- test_layer 0 = unit tests (single file/function)
- test_layer 1 = integration tests (multiple modules)
- test_layer 2 = E2E tests (full system)
- Write REAL, executable test scripts — not pseudocode
- run_command must be a safe command to execute
- Use relative imports when possible
- Tests should assert expected behavior, not just run without checking
- Keep tests focused and fast
"""


def _is_command_allowed(cmd: str) -> bool:
    """Check if a command is safe to execute."""
    # Block shell metacharacters in raw command string
    for meta in BLOCKED_CHARS:
        if meta in cmd:
            return False
    try:
        parts = shlex.split(cmd)
    except ValueError:
        return False  # Malformed command
    if not parts:
        return False
    # Check command base name
    base = parts[0].rsplit("/", 1)[-1]
    if base not in ALLOWED_COMMANDS:
        return False
    # Block dangerous flags
    if any(flag in BLOCKED_FLAGS for flag in parts[1:]):
        return False
    return True


def _execute_command(cmd: str, cwd: Path, timeout: int = EXEC_TIMEOUT) -> dict:
    """Execute a command safely with timeout."""
    result = {
        "command": cmd,
        "returncode": -1,
        "stdout": "",
        "stderr": "",
        "timed_out": False,
    }

    try:
        parts = shlex.split(cmd)
    except ValueError:
        result["stderr"] = "Malformed command"
        return result

    try:
        proc = subprocess.run(
            parts,
            cwd=str(cwd),
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        result["returncode"] = proc.returncode
        result["stdout"] = proc.stdout[-2000:]  # Cap output
        result["stderr"] = proc.stderr[-2000:]
    except subprocess.TimeoutExpired:
        result["timed_out"] = True
        result["stderr"] = f"Command timed out after {timeout}s"
    except Exception as e:
        result["stderr"] = str(e)

    return result


def run_tests(
    source_files: list[dict],
    max_test_layer: int = 2,
    workspace_root: Path | None = None,
) -> dict:
    """
    Generate and execute tests for source files.

    Args:
        source_files: list of {"filepath": ..., "language": ..., "description": ...}
        max_test_layer: highest test layer to run (phase-dependent)
        workspace_root: project root directory

    Returns:
        Summary dict with test results.
    """
    if workspace_root is None:
        workspace_root = PROJECT_ROOT

    if not source_files:
        return {"total_tests": 0, "passed": 0, "failed": 0}

    console.print(
        f"[bold yellow]🧪 Tester AI[/bold yellow] — "
        f"generating tests for {len(source_files)} file(s)"
    )

    # ── Environment Strategy ──────────────────────────────────────────────
    from adelie.env_strategy import detect_env, select_strategy, wrap_command, get_current_phase, ensure_env
    env_profile = detect_env(workspace_root)
    env_profile = ensure_env(env_profile, workspace_root)
    env_strategy = select_strategy(env_profile, phase=get_current_phase())

    # Read source files for context
    file_contents = []
    for finfo in source_files:
        fp = finfo.get("filepath", "")
        full_path = workspace_root / fp
        if full_path.exists():
            try:
                content = full_path.read_text(encoding="utf-8")
                file_contents.append(f"--- {fp} ---\n{content}")
            except Exception:
                pass

    user_prompt = (
        f"## Source Files to Test\n\n"
        + "\n\n".join(file_contents)
        + f"\n\n## Max Test Layer: {max_test_layer}\n"
        f"Generate test scripts. Output a JSON object."
    )

    try:
        raw = generate(
            system_prompt=SYSTEM_PROMPT,
            user_prompt=user_prompt,
            temperature=0.2,
        )
    except Exception as e:
        console.print(f"[red]❌ Tester AI LLM error: {e}[/red]")
        return {"total_tests": 0, "passed": 0, "failed": 0}

    # Parse
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
            except json.JSONDecodeError:
                console.print("[yellow]⚠️  Tester AI — invalid JSON[/yellow]")
                return {"total_tests": 0, "passed": 0, "failed": 0}
        else:
            return {"total_tests": 0, "passed": 0, "failed": 0}

    scripts = data.get("test_scripts", [])
    if not scripts:
        console.print("[dim]  No test scripts generated.[/dim]")
        return {"total_tests": 0, "passed": 0, "failed": 0}

    # Ensure directories
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    total = 0
    passed = 0
    failed = 0
    results_log = []

    for script in scripts:
        layer = script.get("test_layer", 0)
        if layer > max_test_layer:
            console.print(f"  [dim]⏭  Skipped {script.get('name', '?')} (layer {layer})[/dim]")
            continue

        filename = script.get("filename", "")
        content = script.get("content", "")
        name = script.get("name", filename)

        if not filename or not content:
            continue

        # Write test script (ensure parent dirs exist for nested paths)
        script_path = SCRIPTS_DIR / filename
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(content, encoding="utf-8")

        # Build run command from actual saved path (don't trust LLM path)
        lang = script.get("language", "python")
        if lang in ("python", "py"):
            python = env_profile.python_bin or "python"
            run_cmd = f"{python} -m pytest {script_path} -v --tb=short"
        elif lang in ("javascript", "js", "typescript", "ts"):
            ext = script_path.suffix.lower()
            if ext in (".ts", ".tsx", ".jsx"):
                # TypeScript/JSX: use npx tsx to execute directly
                # (vitest's include patterns conflict with Tester AI naming)
                run_cmd = f"npx tsx {script_path}"
            else:
                run_cmd = f"node {script_path}"
        else:
            # Fall back to LLM-provided command if language unknown
            run_cmd = script.get("run_command", f"python {script_path}")

        # Wrap command with environment strategy
        run_cmd = wrap_command(run_cmd, env_profile, env_strategy)

        # Security check
        if not _is_command_allowed(run_cmd):
            console.print(f"  [red]🚫 Blocked: {run_cmd} (not whitelisted)[/red]")
            continue

        # Execute
        console.print(f"  [yellow]▶[/yellow] Running: {name} (layer {layer})")
        exec_result = _execute_command(run_cmd, cwd=workspace_root)

        total += 1
        if exec_result["returncode"] == 0:
            passed += 1
            console.print(f"  [green]✅ PASSED[/green] — {name}")
        else:
            failed += 1
            console.print(f"  [red]❌ FAILED[/red] — {name}")
            if exec_result["stderr"]:
                # Show first 200 chars of error
                err_preview = exec_result["stderr"][:200]
                console.print(f"  [dim]{err_preview}[/dim]")

        results_log.append({
            "name": name,
            "layer": layer,
            "passed": exec_result["returncode"] == 0,
            "execution": exec_result,
        })

    # Save results
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    result_path = RESULTS_DIR / f"test_run_{ts}.md"

    report = (
        f"# Test Results — {datetime.now().isoformat(timespec='seconds')}\n\n"
        f"**Total**: {total} | **Passed**: {passed} | **Failed**: {failed}\n\n"
    )
    for r in results_log:
        icon = "✅" if r["passed"] else "❌"
        report += (
            f"## {icon} {r['name']} (Layer {r['layer']})\n"
            f"- Command: `{r['execution']['command']}`\n"
            f"- Return code: {r['execution']['returncode']}\n"
        )
        if r["execution"]["stdout"]:
            report += f"- Stdout:\n```\n{r['execution']['stdout'][:500]}\n```\n"
        if r["execution"]["stderr"]:
            report += f"- Stderr:\n```\n{r['execution']['stderr'][:500]}\n```\n"
        report += "\n"

    result_path.write_text(report, encoding="utf-8")

    console.print(
        f"[bold yellow]🧪 Tester AI[/bold yellow] — "
        f"{passed}/{total} passed, {failed} failed"
    )

    # Build failure summary for coder feedback loop
    failure_summary = ""
    if failed > 0:
        lines = [f"TEST FAILURES: {failed}/{total} tests failed.\n"]
        for r in results_log:
            if not r["passed"]:
                lines.append(f"❌ {r['name']} (Layer {r['layer']}):")
                stderr = r["execution"].get("stderr", "")
                stdout = r["execution"].get("stdout", "")
                if stderr:
                    lines.append(f"  Error: {stderr[:300]}")
                if stdout:
                    lines.append(f"  Output: {stdout[:300]}")
                lines.append("")
        failure_summary = "\n".join(lines)

    return {"total_tests": total, "passed": passed, "failed": failed, "results": results_log, "failure_summary": failure_summary}
